name: Client CI

on:
  pull_request:
    branches: [main, development, staging]
    paths:
      - 'client/**'
      - '.github/workflows/client.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Audit for vulnerabilities
        working-directory: client
        run: npx audit-ci --moderate --report-type summary --skip-dev true

      - name: Install dependencies
        working-directory: client
        run: yarn

      - name: Unit tests
        working-directory: client
        run: yarn run test:ci

      - name: Linting
        working-directory: client
        run: yarn run lint

      - name: Build
        working-directory: client
        run: yarn run build
